//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfesBetGUI.EfesBetServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EfesBetServiceReference.IEfesBet")]
    public interface IEfesBet {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEfesBet/GetMatch", ReplyAction="http://tempuri.org/IEfesBet/GetMatchResponse")]
        EfesBet.DataContract.GetMatchDetailsDC[] GetMatch();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEfesBetChannel : EfesBetGUI.EfesBetServiceReference.IEfesBet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EfesBetClient : System.ServiceModel.ClientBase<EfesBetGUI.EfesBetServiceReference.IEfesBet>, EfesBetGUI.EfesBetServiceReference.IEfesBet {
        
        public EfesBetClient() {
        }
        
        public EfesBetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EfesBetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EfesBetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EfesBetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EfesBet.DataContract.GetMatchDetailsDC[] GetMatch() {
            return base.Channel.GetMatch();
        }
    }
}
